---
title: "Multipoverty"
author: "Gruppo F"
format: html
---

# CONFRONTO SUB-SAHARAN AFRICA CON IL MONDO

```{r}
install.packages("psych")
library(psych)
install.packages("jsonlite")
library(jsonlite)
hdi.ssa <- fromJSON("hdr-data.json")
hdi.ssa <- hdi.ssa[, c(2,8,11)]
names(hdi.ssa)[names(hdi.ssa) == "value"] <- "HDI"
hdi.ssa$year <- as.integer(hdi.ssa$year)
hdi.ssa$HDI <- as.numeric(hdi.ssa$HDI)

hdi.w <- fromJSON("hdi.world.json")
hdi.w <- hdi.w[, c(2,8,11)]
names(hdi.w)[names(hdi.w) == "value"] <- "HDI"
hdi.w$year <- as.integer(hdi.w$year)
hdi.w$HDI <- as.numeric(hdi.w$HDI)



hdi <- rbind(hdi.ssa, hdi.w)
ggplot(hdi, aes(x = year, y = HDI, color = country)) +
  geom_line(size = 1.2) +
  labs(
    title = "HDI Sub-Saharan Africa vs World",
    x = "Anno",
    y = "HDI",
    color = "Legenda"
  ) +
  scale_x_continuous(breaks = seq(1990, 2023, by = 5)) +
  scale_y_continuous(breaks = seq(0.4, 0.8, by = 0.05)) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

# CONFRONTO TRA SUDAFRICA, NIGERIA, GHANA, SENEGAL 

```{r}
#NIGERIA
hdi.nga <- fromJSON("hdi.NGA.json")
hdi.nga <- hdi.nga[, c(2,8,11)]
names(hdi.nga)[names(hdi.nga) == "value"] <- "HDI"
hdi.nga$year <- as.integer(hdi.nga$year)
hdi.nga$HDI <- as.numeric(hdi.nga$HDI)

#GHANA
hdi.gha <- fromJSON("hdi.gha.json")
hdi.gha <- hdi.gha[, c(2,8,11)]
names(hdi.gha)[names(hdi.gha) == "value"] <- "HDI"
hdi.gha$year <- as.integer(hdi.gha$year)
hdi.gha$HDI <- as.numeric(hdi.gha$HDI)

#SENEGAL
hdi.sen <- fromJSON("hdi.sen.json")
hdi.sen <- hdi.sen[, c(2,8,11)]
names(hdi.sen)[names(hdi.sen) == "value"] <- "HDI"
hdi.sen$year <- as.integer(hdi.sen$year)
hdi.sen$HDI <- as.numeric(hdi.sen$HDI)

#SUDAFRICA
#NIGERIA
hdi.nga <- fromJSON("hdi.NGA.json")
hdi.nga <- hdi.nga[, c(2,8,11)]
names(hdi.nga)[names(hdi.nga) == "value"] <- "HDI"
hdi.nga$year <- as.integer(hdi.nga$year)
hdi.nga$HDI <- as.numeric(hdi.nga$HDI)

#GHANA
hdi.gha <- fromJSON("hdi.gha.json")
hdi.gha <- hdi.gha[, c(2,8,11)]
names(hdi.gha)[names(hdi.gha) == "value"] <- "HDI"
hdi.gha$year <- as.integer(hdi.gha$year)
hdi.gha$HDI <- as.numeric(hdi.gha$HDI)

#SENEGAL
hdi.zaf <- fromJSON("hdi.zaf.json")
hdi.zaf <- hdi.zaf[, c(2,8,11)]
names(hdi.zaf)[names(hdi.zaf) == "value"] <- "HDI"
hdi.zaf$year <- as.integer(hdi.zaf$year)
hdi.zaf$HDI <- as.numeric(hdi.zaf$HDI)

#GRAFICO 3 paesi a confronto
hdi_3 <- rbind(hdi.nga, hdi.gha, hdi.sen, hdi.zaf, hdi.ssa)
ggplot(hdi_3, aes(x = year, y = HDI, color = country)) +
  geom_line(size = 1.2) +
  labs(
    title = "HDI Nigeria, Ghana, Senegal, Sudafrica",
    x = "Anno",
    y = "HDI",
    color = "Paese"
  ) +
  scale_x_continuous(breaks = seq(1990, 2023, by = 5)) +
  scale_y_continuous(breaks = seq(0.4, 0.8, by = 0.05)) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) 
d_hdi_3 <- (describe(hdi_3)) 
View(d_hdi_3)

```


## GDP PER CAPITA per i 4 paesi a confronto
```{r}
install.packages("readxl")
library(readxl)
library(tidyr)
library(dplyr)
gdp <- read_excel("gdp.xlsx")
gdp <- gdp[c(1:5),c(-1,-2,-4)]

names(gdp)
if ("Country Name" %in% names(gdp)) {
  names(gdp)[names(gdp) == "Country Name"] <- "Country.Name"
}

gdp[ , -1] <- lapply(gdp[ , -1], function(x) as.numeric(as.character(x)))
gdp_long <- gdp %>%
  pivot_longer(
    cols = -Country.Name,
    names_to = "year",
    values_to = "gdp"
  )
gdp_long$year <- as.integer(sub("\\[.*", "", gdp_long$year))



ggplot(gdp_long, aes(x = year, y = gdp, color = Country.Name)) +
  geom_line(size = 1.2) +
  labs(
    title = "GDP per capita (current US$)",
    x = "Anno",
    y = "GDP per capita (current US$)",
    color = "Paese"
  ) +
  theme_minimal()
d_gdp <- (describe(gdp)) 
View(d_gdp)

```

# FERTILITÀ
```{r}
fert <- read_excel ("fert.xlsx")
fert <- fert[c(1:4),c(-2,-3,-4)]
names(fert)
if ("Country Name" %in% names(fert)) {
  names(fert)[names(fert) == "Country Name"] <- "Country.Name"
}

fert[ , -1] <- lapply(fert[ , -1], function(x) as.numeric(as.character(x)))
fert_long <- fert %>%
  pivot_longer(
    cols = -Country.Name,
    names_to = "year",
    values_to = "Fertility"
  )
fert_long$year <- as.integer(sub("\\[.*", "", fert_long$year))

ggplot(fert_long, aes(x = year, y = Fertility, color = Country.Name)) +
  geom_line(size = 1.2) +
  labs(
    title = "Fertility rate",
    x = "Anno",
    y = "Fertility rate",
    color = "Paese"
  ) +
  theme_minimal()
d_fert <- describe(fert)
View(d_fert)
```


# ACQUA
```{r}
wat <- read_excel ("Acqua.xlsx")
wat <- wat[c(1:4),c(-2,-3,-4)]
wat <- wat[,c(1,12:ncol(wat))]
names(wat)
if ("Country Name" %in% names(wat)) {
  names(wat)[names(wat) == "Country Name"] <- "Country.Name"
}

wat[ , -1] <- lapply(wat[ , -1], function(x) as.numeric(as.character(x)))
wat_long <- wat %>%
  pivot_longer(
    cols = -Country.Name,
    names_to = "year",
    values_to = "Acqua"
  )
wat_long$year <- as.integer(sub("\\[.*", "", wat_long$year))

ggplot(wat_long, aes(x = year, y = Acqua, color = Country.Name)) +
  geom_line(size = 1.2) +
  labs(
    title = "Acqua",
    x = "Anno",
    y = "Acqua",
    color = "Paese"
  ) +
  theme_minimal()
d_wat <- describe(wat)
View(d_wat)

```


# TASSO DI MORTALITÀ 
```{r}
mort <- read_excel ("tasso di mort.xlsx")
mort <- mort[c(1:8),c(-2,-3,-4)]
library(dplyr)

names(mort)
if ("Country Name" %in% names(mort)) {
  names(mort)[names(mort) == "Country Name"] <- "Country.Name"
}

mort[ , -1] <- lapply(mort[ , -1], function(x) as.numeric(as.character(x)))

mort_long <- mort %>%
  pivot_longer(cols = -Country.Name, names_to = "year", values_to = "Mortality")

mort_long$year <- as.integer(sub("\\[.*", "", mort_long$year))

mort_final <- mort_long %>%
  group_by(Country.Name, year) %>%
  summarise(Mortality = mean(Mortality, na.rm = TRUE))

ggplot(mort_final, aes(x = year, y = Mortality, color = Country.Name)) +
  geom_line(size = 1.2) +
  labs(
    title = "Tasso di mortalità",
    x = "Anno",
    y = "Tasso di mortalità",
    color = "Paese"
  ) +
  theme_minimal()
d_mort <- describe(mort)
View(d_mort)

```
ciao ciao speriamo di risolvere

# POPOLAZIONE
```{r}
pop <- read_excel ("pop.xlsx")
pop <- pop[c(1:4),c(-2,-3,-4)]
names(pop)
if ("Country Name" %in% names(pop)) {
  names(pop)[names(pop) == "Country Name"] <- "Country.Name"
}

pop[ , -1] <- lapply(pop[ , -1], function(x) as.numeric(as.character(x)))
pop_long <- pop %>%
  pivot_longer(
    cols = -Country.Name,
    names_to = "year",
    values_to = "Population"
  )
pop_long$year <- as.integer(sub("\\[.*", "", pop_long$year))

ggplot(pop_long, aes(x = year, y = Population, color = Country.Name)) +
  geom_line(size = 1.2) +
  labs(
    title = "Popolazione",
    x = "Anno",
    y = "Popolazione",
    color = "Paese"
  ) +
  theme_minimal()
d_pop <- describe(pop)
View(d_pop)
```

# ELETTRICITÀ

```{r}
elet <- read_excel ("accesso elettricità.xlsx")
elet <- elet[c(1:4),c(-2,-3,-4)]
elet <- wat[,c(1,8:ncol(wat))]
names(elet)
if ("Country Name" %in% names(elet)) {
  names(elet)[names(elet) == "Country Name"] <- "Country.Name"
}

elet[ , -1] <- lapply(elet[ , -1], function(x) as.numeric(as.character(x)))
elet_long <- elet %>%
  pivot_longer(
    cols = -Country.Name,
    names_to = "year",
    values_to = "Electricity"
  )
elet_long$year <- as.integer(sub("\\[.*", "", elet_long$year))

ggplot(elet_long, aes(x = year, y = Electricity , color = Country.Name)) +
  geom_line(size = 1.2) +
  labs(
    title = "Electricità",
    x = "Anno",
    y = " Accesso all'elettricità",
    color = "Paese"
  ) +
  theme_minimal()
d_elet <- describe(elet)
View(d_elet)
```

# INVESTIMENTI STRANIERI

```{r}
invst <- read_excel("investimenti stranieri.xlsx")
invst <- invst[c(1:4), c(-2, -3, -4)]

if ("Country Name" %in% names(invst)) {
  names(invst)[names(invst) == "Country Name"] <- "Country.Name"
}

invst[ , -1] <- lapply(invst[ , -1], function(x) as.numeric(as.character(x)))

invst_long <- invst %>%
  pivot_longer(
    cols = -Country.Name,
    names_to = "year",
    values_to = "Investimenti_Stranieri"   # safe name (no spaces)
  )

invst_long$year <- as.integer(sub("\\[.*", "", invst_long$year))

ggplot(invst_long, aes(x = year, y = Investimenti_Stranieri, color = Country.Name)) +
  geom_line(size = 1.2) +
  labs(
    title = "Investimenti stranieri",
    x = "Anno",
    y = "Investimenti stranieri",
    color = "Paese"
  ) +
  theme_minimal()
d_invst <- describe(invst)
View(d_invst)
```
